CREATE TABLE CUSTOMERS
(
ID INT NOT NULL AUTO_INCREMENT,
NAME varchar(100),
CITY varchar(100),
INSERTIONDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO CUSTOMERS (NAME, CITY) VALUES ('ConTe.it', 'Roma');
INSERT INTO CUSTOMERS (NAME, CITY) VALUES ('Acea', 'Roma');
INSERT INTO CUSTOMERS (NAME, CITY) VALUES ('Telecom', 'Pomezia');

CREATE TABLE EMPLOYEES (
ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(40),
SURNAME VARCHAR(40),
BIRTHDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO EMPLOYEES (NAME, SURNAME) VALUES ('Giovanni', 'Mezzullo');
INSERT INTO EMPLOYEES (NAME, SURNAME) VALUES ('Andrea', 'Artuso');
INSERT INTO EMPLOYEES (NAME, SURNAME) VALUES ('Antonio', 'Roberti');
INSERT INTO EMPLOYEES (NAME, SURNAME) VALUES ('Valerio', 'Speziale');

CREATE TABLE EMPLOYEES_CUSTOMERS (
ID INT NOT NULL AUTO_INCREMENT,
EMPLOYEES_ID INT NOT NULL,
CUSTOMERS_ID INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO EMPLOYEES_CUSTOMERS (EMPLOYEES_ID, CUSTOMERS_ID) VALUES (1, 1);
INSERT INTO EMPLOYEES_CUSTOMERS (EMPLOYEES_ID, CUSTOMERS_ID) VALUES (1, 3);
INSERT INTO EMPLOYEES_CUSTOMERS (EMPLOYEES_ID, CUSTOMERS_ID) VALUES (4, 2);
INSERT INTO EMPLOYEES_CUSTOMERS (EMPLOYEES_ID, CUSTOMERS_ID) VALUES (3, 3);