INSERT INTO EMPLOYEES_CUSTOMERS (EMPLOYEES_ID, CUSTOMERS_ID) VALUES (1, 1);
INSERT INTO EMPLOYEES_CUSTOMERS (EMPLOYEES_ID, CUSTOMERS_ID) VALUES (1, 3);
INSERT INTO EMPLOYEES_CUSTOMERS (EMPLOYEES_ID, CUSTOMERS_ID) VALUES (4, 2);
INSERT INTO EMPLOYEES_CUSTOMERS (EMPLOYEES_ID, CUSTOMERS_ID) VALUES (3, 3);